candidates = Candidate.create([{ handle: '@HillaryClinton', instagram_link:"https://www.instagram.com/hillaryclinton/",facebook_link:"https://www.facebook.com/hillaryclinton/", location:"Chappaqua, New York" ,picture:"http://s.wsj.net/public/resources/images/BN-HV154_DEMTRA_G_20150410102104.jpg" , party: 'Democratic', first_tweet: "Thanks for the inspiration @ASmith83 & @Sllambe - I'll take it from here... #tweetsfromhillary"}, 
  { handle: '@BernieSanders', location:"Burlington, Vermont" , instagram_link:"https://www.instagram.com/berniesanders/", facebook_link:"https://www.facebook.com/berniesanders/", picture:"http://s.wsj.net/public/resources/images/BN-IE317_sander_G_20150430093139.jpg" , party: 'Democratic', first_tweet: "The campaign is now on Twitter - and looking for input! What would you like to see here?"}, 
  { handle: '@MartinOMalley', location:"Baltimore, Maryland" , instagram_link:"https://www.instagram.com/martinomalley/" , facebook_link:"https://www.facebook.com/MartinOMalley/", picture:"http://s.wsj.net/public/resources/images/BN-HV156_DEMTRA_G_20150410102318.jpg" , party: 'Democratic', first_tweet: "can't wait to get to Denver - it's going to be a really great week. keep checking back - many more updates to follow"},
  { handle: '@realDonaldTrump', location: "Manhattan, New York", instagram_link:"https://www.instagram.com/realdonaldtrump/" , facebook_link:"https://www.facebook.com/DonaldTrump/",  picture:"http://s.wsj.net/public/resources/images/BN-IY192_TRUMP__G_20150616114737.jpg" , party: 'Republican', first_tweet: "Be sure to tune in and watch Donald Trump on Late Night with David Letterman as he presents the Top Ten List tonight!"},
  { handle: '@marcorubio',location: "West Miami, Florida" , instagram_link:"https://www.instagram.com/marcorubiofla/?hl=en" , facebook_link:"https://www.facebook.com/MarcoRubio/", picture:"http://s.wsj.net/public/resources/images/BN-GT306_GOPCAR_G_20150202121338.jpg" , party: 'Republican', first_tweet: "Gov. Pawlenty was impressive this morning at gopac"},
  { handle: '@RandPaul', location: "Bowling Green, Kentucky", instagram_link:"https://www.instagram.com/drrandpaul/" , facebook_link:"https://www.facebook.com/RandPaul/", picture:"http://s.wsj.net/public/resources/images/BN-GY255_GOPCAR_G_20150212171554.jpg" , party: 'Republican', first_tweet: "Here is a video of my inaugural statement: http://bit.ly/dHYJGG"},
  { handle: '@RickSantorum', location:"Mount Lebanon, Pennsylvania" , instagram_link:"https://www.instagram.com/ricksantorum/", facebook_link:"https://www.facebook.com/RickSantorum/",  picture:"http://s.wsj.net/public/resources/images/BN-GY265_GOPCAR_G_20150212173023.jpg" , party: 'Republican', first_tweet: "Friday i start as the permanent host of the Bill Bennett radio show.  Tune in 6am ET.  Healthcare wil be the focus."},
  { handle: '@JohnKasich', location: "Westerville, Ohio" , instagram_link:"https://www.instagram.com/johnkasich/", facebook_link:"https://www.facebook.com/JohnKasich/", picture:"http://s.wsj.net/public/resources/images/BN-JM353_KASICH_G_20150721112452.jpg" , party: 'Republican', first_tweet: "is using Twitter for the first time."},
  { handle: '@JebBush', location:"Miami, Florida" , instagram_link:"https://www.instagram.com/jebbush/", facebook_link:"https://www.facebook.com/jebbush/", picture:"http://s.wsj.net/public/resources/images/BN-GT311_GOPCAR_G_20150202122001.jpg", party: 'Republican', first_tweet: "Kudos to the Florida Senate leadership for their bold education agenda this session.  Follow us at www.foundationforfloridasfuture.org."},
  { handle: '@RealBenCarson', location: "Baltimore, Maryland", instagram_link:"https://www.instagram.com/realbencarson/" , facebook_link:"https://www.facebook.com/realbencarson/",  picture: "http://s.wsj.net/public/resources/images/BN-GY266_GOPCAR_G_20150212173216.jpg" , party: 'Republican', first_tweet: "Today I've officially joined the twitterverse."},
  { handle: '@ChrisChristie', location:"Mendham, New Jersey", instagram_link:"https://www.instagram.com/chrischristie/" , facebook_link:"https://www.facebook.com/govchristie/", picture:"http://s.wsj.net/public/resources/images/BN-GT309_GOPCAR_G_20150202121742.jpg" , party: 'Republican', first_tweet: "one just wasn't enough - 4 more years... Let's do this, NJ! #NJGov #strongleadership"},
  { handle: '@CarlyFiorina', location:"Los Altos Hills, California" , instagram_link:"https://www.instagram.com/carlyforamerica/" , facebook_link:"https://www.facebook.com/CarlyFiorina/", picture:"http://s.wsj.net/public/resources/images/BN-GT280_GOPCAR_G_20150202114634.jpg" , party: 'Republican', first_tweet: "Carlyfornia Dreamin’!!! Check it out today at CarlyforCalifornia.com"},
  { handle: '@GovMikeHuckabee', location:"North Little Rock, Arkansas", instagram_link:"https://www.instagram.com/govmikehuckabee/" ,  facebook_link:"https://www.facebook.com/mikehuckabee/", picture:"http://s.wsj.net/public/resources/images/BN-GT282_GOPCAR_G_20150202114759.jpg" , party: 'Republican', first_tweet: "Hope to see many friends in Bethesda tomorrow morning (bright and early!) 8:30am at Doubletree Hotel Wisconsin Ave"}
  ])
